version: "2"
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=dIMA123456
      - MYSQL_DATABASE=costlocator
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mysql
  app:
    image: grdo/costlocator:latest
    restart: always
    links:
      - db
    ports:
      - 8000:8000
volumes:
  my-datavolume:



