version: "2"
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=dIMA123456
      - MYSQL_DATABASE=coslocator
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    ports:
      - 3306:3306
  app:
    depends_on:
      - db
    ports:
      - 8000:8000



