version: "2"
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=dIMA123456
      - MYSQL_DATABASE=coslocator
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    ports:
      - 3306:3306
  app:
    image: costlocator:2
    restart: always
    links:
      - db
    ports:
      - 8000:8000



